server:
  port: 9000
  
  
spring:
  application:
    name: GATEWAY-SERVICE
    
    
    
    
  cloud:
    gateway:
     globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:9097" #client application orifin
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowedHeaders: ["Authorization","Content-Type"]
                         
             
    
    
    
 # cloud:
 #   gateway:
 #     routes:
 #     - id: client-service
 #       uri: lb://CLIENT-SERVICE
 #       predicates:
 #       - name: Path
 #         args:
  #          Path: /
  #          
            
 #     - id: old-service
 #       uri: lb://OLD-SERVICE
 #       predicates:
 #       - name: Path
  #        args:
  #          Path: /myprofile/*
             
             
           
    
    
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
  instance:
    hostname: localhost